# Config for EleutherEvalRecipe in eleuther_eval.py
#
# To launch, run the following command from root torchtune directory:
#    tune run eleuther_eval --config eleuther_evaluation tasks=["truthfulqa_mc2","hellaswag"]

output_dir: ./ # Not needed

# Model Arguments
model:
  _component_: torchtune.models.qwen3.qwen3_8b_base

checkpointer:
  _component_: torchtune.training.FullModelTorchTuneCheckpointer
  checkpoint_dir: outputs/qwen/256/pissaquant
  checkpoint_files: [
    model-00001-of-00001.pt
  ]
  recipe_checkpoint: null
  output_dir: outputs # Not used
  model_type: QWEN3

# Tokenizer
tokenizer:
  _component_: torchtune.models.qwen3.qwen3_tokenizer
  path: /ceph/home/muhan01/huggingfacemodels/Qwen3-8B/vocab.json
  merges_file: /ceph/home/muhan01/huggingfacemodels/Qwen3-8B/merges.txt
  max_seq_len: null

# Environment
device: cuda
dtype: bf16
seed: 1234 # It is not recommended to change this seed, b/c it matches EleutherAI's default seed

# EleutherAI specific eval args
# tasks: ["hellaswag", "wikitext"]
tasks: ["hellaswag", "wikitext", "arc_easy", "arc_challenge", "openbookqa", "piqa", "winogrande", "paloma_ptb", "boolq"]
# tasks: ["wikitext"]
limit: null
max_seq_length: 4096
batch_size: 1
enable_kv_cache: True

quantizer: null
